export const HEALTH_TIMEOUT = 3_000
export const HEALTH_SHOW_TOAST_AFTER = 800
export const HEALTH_SUCCESS_TOAST_DURATION = 1_500
export const HEALTH_MAX_WAIT_TIME = 2 * 60 * 1000
export const HEALTH_RETRY_INTERVAL = 2_000
export const HEALTH_MESSAGE_INTERVAL = 3_500